version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb+srv://ardeb:ardeb@cluster0-njbm3.mongodb.net/food-ordering-app-api?retryWrites=true&w=majority
      - JWT_SECRET=thisisakeytoalltheprivatedata
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb+srv://ardeb:ardeb@cluster0-njbm3.mongodb.net/food-ordering-app-api-test?retryWrites=true&w=majority
      - JWT_SECRET=thisisakeytoalltheprivatedata
    command: ["npm","run","test"]